AMAPG4/Models/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace AMAPG4.Models
{
    public class Producer
    {
        [Required(ErrorMessage = "Le numéro SIRET est obligatoire.")]
        [StringLength(14, MinimumLength = 14, ErrorMessage = "Le numéro SIRET doit comporter 14 chiffres.")]
        [RegularExpression(@"^\d{14}$", ErrorMessage = "Le numéro SIRET doit contenir uniquement 14 chiffres.")] 
        public string Siret { get; set; }
        [Required(ErrorMessage = "Le nom est obligatoire.")]
        [MinLength(2), MaxLength(50)]
        public string ContactName { get; set; }

        [Required(ErrorMessage = "Le RIB est obligatoire.")]
        [StringLength(23, MinimumLength = 23, ErrorMessage = "Le RIB doit comporter 23 caractères.")]
        [RegularExpression(@"^[A-Za-z0-9]{23}$", ErrorMessage = "Le RIB doit contenir exactement 23 caractères alphanumériques.")]
        public string RIB { get; set; }
        UserAccount Account { get; set; }
    }
}

AMAPG4/Models/User/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace AMAPG4.Models.User
{
    public class Producer
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Le numéro SIRET est obligatoire.")]
        [StringLength(14, MinimumLength = 14, ErrorMessage = "Le numéro SIRET doit comporter 14 chiffres.")]
        [RegularExpression(@"^\d{14}$", ErrorMessage = "Le numéro SIRET doit contenir uniquement 14 chiffres.")]
        public string Siret { get; set; }
        [Required(ErrorMessage = "Le nom est obligatoire.")]
        [MinLength(2), MaxLength(50)]
        public string ContactName { get; set; }
        public string Description { get; set; }
        public string ProductionType { get; set; }

        [Required(ErrorMessage = "Le RIB est obligatoire.")]
        [RegularExpression(@"^[A-Za-z0-9]{23}$", ErrorMessage = "Le RIB doit contenir exactement 23 caractères alphanumériques.")]
        public string RIB { get; set; }
        public string ImagePath { get; set; }
        public virtual UserAccount Account { get; set; }
    }
}

AMAPG4/ViewModels/ProducerViewModel.cs
using AMAPG4.Models.User;
using AMAPG4.Models.Catalog;
using System.Collections.Generic;

namespace AMAPG4.ViewModels
{
    public class ProducerViewModel
    {

        public UserAccount Account { get; set; }
        public Producer Producers { get; set; }

        public List<Producer> ProducersList { get; set; } 
        public List<Product> Products { get; set; }
        public int Id { get; set; }
      
     
       
    }
}

AMAPG4/Controllers/ProducerController.cs
using AMAPG4.Models.User;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Linq;

using AMAPG4.ViewModels;
using AMAPG4.Models.Command;
using System.Collections.Generic;
using AMAPG4.Models.Catalog;
using Microsoft.AspNetCore.Authorization;
using AMAPG4.Models;


namespace AMAPG4.Controllers
{
	public class ProducerController : Controller
	{
        public MyDBContext _BddContext;
		public ProducerDal _producerDal;
        public ProducerController()
        {
            _producerDal = new ProducerDal();
        }

        public IActionResult Index(string searchString)
		{
            ProducerViewModel viewModel = new ProducerViewModel();
            viewModel.ProducersList=_producerDal.GetAllProducers();
             
           
			// Search using the search bar
			if (!string.IsNullOrEmpty(searchString))
			{
                viewModel.ProducersList = viewModel.ProducersList.Where(p => p.ContactName.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
			}
			return View(viewModel);

		}
     
		public IActionResult ProducerView(int id)
		{


            Producer producer =_producerDal.GetProducerById(id);
            Console.WriteLine(producer.Id);

           

			if (producer == null)
			{
				return NotFound();
			}
            ProducerViewModel model = new ProducerViewModel
            {
                Producers = producer,
                Id = id,
         
                
                Account=producer.Account,
            };
            using (ProductDal productDal = new ProductDal())
            {
                model.Products = productDal.GetAllProductByProducer(producer.Id);
            }
            return View(model);
		}

		[Authorize(Roles = "Admin")]
		// Action pour afficher le formulaire de mise à jour d'un producteur
		[HttpGet]
        public IActionResult Update(int id)
        {
            Producer producer = _producerDal.GetProducerById(id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }
        [Authorize(Roles = "Admin")]
        // Action pour mettre à jour un producteur
        [HttpPost]
        public IActionResult Update(Producer model)
        {
            ModelState.Remove("Account.Password");

            if (ModelState.IsValid)
            {
                Producer producer = _producerDal.GetProducerById(model.Id);

                if (producer != null)
                {
                    producer.Siret = model.Siret;
                    producer.ContactName = model.ContactName;
                    producer.Description = model.Description;
                    producer.ProductionType = model.ProductionType;
                    producer.RIB = model.RIB;
                    producer.Account.Address = model.Account.Address;
                    producer.Account.Email = model.Account.Email;
                    producer.Account.Phone = model.Account.Phone;
                    producer.Account.Name = model.Account.Name;

                    _producerDal.UpdateProducer(producer);
                }
            }
            return RedirectToAction("Read", new { id = model.Id });
        }
        [Authorize(Roles = "Admin")]
        // Action pour supprimer un producteur
        [HttpPost]
        public IActionResult Delete(Producer model)
        {
            Producer producer = _producerDal.GetProducerById(model.Id);
            Console.WriteLine(producer);
            if (producer == null)
            {
                Console.WriteLine("Producer not found");
                return NotFound();
            }
            Console.WriteLine("Producer found");
       
            using (ProductDal productDal = new ProductDal())
            {
                List<Product> products = productDal.GetAllProductByProducer(model.Id);
                foreach(Product product in products)
                {
                    productDal.DeleteProduct(product.Id);
                }
            }
            _producerDal.DeleteProducer(producer.Id);
            return RedirectToAction("Producers", "Dashboard");
        }
        [Authorize(Roles = "Admin")]
        // Action pour créer un nouveau producteur
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
		[Authorize(Roles = "Admin")]
		[HttpPost]
        public IActionResult Create(Producer model)
        {
            foreach (string key in ModelState.Keys.ToList())
            {
                bool isValid = !ModelState[key].Errors.Any();

                if (isValid)
                {
                    Console.WriteLine($"{key}: true");
                }
                else
                {
                    Console.WriteLine($"{key}: false");
                }
            }
            if (ModelState.IsValid)
            {
                int newId = _producerDal.CreateProducer(
                    model.Siret,
                    model.ContactName,
                    model.Description,
                    model.ProductionType,
                    model.RIB,
                    model.ImagePath,
                    model.Account.Email,
                    model.Account.Password,
                    model.Account.Name,
                    model.Account.Address,
                    model.Account.Phone);

                return RedirectToAction("Read", new { id = newId });
            }
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        // Action pour lire les détails d'un producteur
        [HttpGet]
        public IActionResult Read(int id)
        {
            Producer producer = _producerDal.GetProducerById(id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }
        public IActionResult MyProduct()
        {

            UserAccountViewModel UserAccountViewModel =
        new UserAccountViewModel();
            ProducerViewModel ProducerViewModel = new ProducerViewModel();
            using (UserAccountDal userAccountDal = new UserAccountDal())
            {
                UserAccountViewModel.UserAccount = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name);
            }
            using (ProducerDal producerDal = new ProducerDal())
            {
                Producer producer = producerDal.GetProducerByUserAccount(UserAccountViewModel.UserAccount.Id);
                ProducerViewModel.Producers = producer;
            }
            using (ProductDal productDal = new ProductDal())
            {
                List<Product> products = productDal.GetAllProductByProducer(ProducerViewModel.Producers.Id);
                ProducerViewModel.Products = products;
                using(OrderLineDal orderLineDal = new OrderLineDal())
                {

              
                foreach (Product product in products) {
                    List<OrderLine> orders = orderLineDal.GetOrderLineByProduct(product.Id);
                        product.TotalSales = 0;
                        product.LastMonthSale = 0;
                        TimeSpan time = new TimeSpan(30, 0, 0, 0);
                        foreach (OrderLine orderLine in orders)
                        {
                            if (orderLine.orderLineType == OrderLineType.Paid)
                            {
                                product.TotalSales=orderLine.Quantity+product.TotalSales;
                                if((orderLine.DateTime - DateTime.Now < time)) {
                                    product.LastMonthSale=orderLine.Quantity+product.LastMonthSale;
                                        

                                }
                            }
                                
                            
                        }
                        }
                }
            }



            return View(ProducerViewModel);
        }

    }
}

AMAPG4/Views/Producer/Create.cshtml
@model AMAPG4.Models.User.Producer

@{
    ViewBag.Title = "Créer un nouveau compte Producteur";
    Layout = "_BackOfficeLayout";
}
<div class="user-profile-form-container">
    <div class="user-profile">
        <h1 class="bo-entity">Créer un nouveau compte Producteur</h1>


@using (Html.BeginForm("Create", "Producer", FormMethod.Post))
{
    <div class="user-info">
        @Html.LabelFor(m => m.Account.Name, "Nom de l'exploitation")
        @Html.TextBoxFor(model => model.Account.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Account.Name)
    </div>
    <div class="user-info">
        <label>Type de production :</label>
        @Html.TextBoxFor(model => model.ProductionType, new { @class = "form-control" })
    </div>

    <div class="user-info">
        <label>Nom du contact :</label>
        @Html.TextBoxFor(model => model.ContactName, new { @class = "form-control" })
    </div>
    <div class="user-info">
        <label>Description :</label>
        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
    </div>

    <div class="user-info">
        <label>Email :</label>
        @Html.TextBoxFor(model => model.Account.Email, new { @class = "form-control" })
    </div>

    <div class="user-info">
        <label>Téléphone :</label>
        @Html.TextBoxFor(model => model.Account.Phone, new { @class = "form-control" })
    </div>

    <div class="user-info">
        <label>Adresse :</label>
        @Html.TextBoxFor(model => model.Account.Address, new { @class = "form-control" })
    </div>

    <div class="user-info">
        @Html.LabelFor(m => m.Siret, "Numéro de SIRET")
        @Html.TextBoxFor(model => model.Siret, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Siret)
    </div>

    <div class="user-info">
        @Html.LabelFor(m => m.RIB, "RIB")
        @Html.TextBoxFor(model => model.RIB, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.RIB)
    </div>

    <div class="user-info">
        <label>Mot de passe :</label>
        @Html.PasswordFor(model => model.Account.Password, new { @class = "form-control" })
    </div>

    <div class="user-actions">
        <button type="submit" class="btn-save">Créer</button>
    </div>
}
    </div>
</div>

AMAPG4/Views/Producer/Index.cshtml
@using System.Globalization
@using AMAPG4.Models.User

@model AMAPG4.ViewModels.ProducerViewModel
@{
    ViewBag.Title = "Catalogue des Producteurs";
    Layout = "_Layout";
}

    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/laFerme.css" />

<div class="producer-body">
    <h2> Nos producteurs</h2>

    <p class="txt-intro">
        Ces producteurs collaborent avec Mon Panier Paysan pour créer un réseau local d'approvisionnement, permettant aux membres de bénéficier de produits frais, de qualité, et de soutenir une agriculture durable et respectueuse de l'environnement.
        Nos producteurs sont situés à moins de 50 km de notre lieu de distribution (35 km à vol d'oiseau), et les livraisons sont regroupées pour minimiser leurs trajets.
    </p>

    <div class="presentation-producer-bottom">


            <form method="get" action="@Url.Action("Index", "Producer")">
                <!-- Search bar -->
                <input type="text" name="searchString" class="search-bar" placeholder="Rechercher un producteur..." />
            </form>


        <!-- Producers -->
        <div class="producer-container">

            @foreach (Producer producer in Model.ProducersList)
            {
                <div class="producer-card">
                    <a href="@Url.Action("ProducerView", "Producer", new { id = producer.Id })">
                        <img class="producer-photo" src="@producer.ImagePath" />
                    </a>
                    <div class="producer-name">@producer.Account.Name</div>
                    <div class="producer-type">@producer.ProductionType</div>
                </div>
                    
            }

        </div>
    </div>
</div>

AMAPG4/Views/Producer/MyProduct.cshtml
@using AMAPG4.Models.Catalog
@using System.Globalization
@model AMAPG4.ViewModels.ProducerViewModel
@{
    ViewBag.Title = "Mon Compte";
    Layout = "_Layout";
}

<title>Mes Produits</title>
<link rel="stylesheet" href="~/css/global.css" />
<link rel="stylesheet" href="~/css/styles.css" />
<link rel="stylesheet" href="~/css/laFerme.css" />
<div>
    <div class="margin-top-table-product">
<table class="table-product">
    
    <thead>
    <tr>
        <th>Nom du produit</th>
      
        <th>Stock</th>

        <th>Prix</th>
        <th>Date Limite</th>
        <th> Vente les 30 derniers jours</th>
                <th> Vente Total</th>
    </tr>
    </thead>
    <tbody>
    @foreach (Product product in Model.Products)
    {
        
        <tr>
            <td>@product.ProductName</td>
     
            <td>@product.Stock</td>

            <td>@product.Price</td>
            <td>@product.LimitDate.ToShortDateString()</td>
                    <td>@product.LastMonthSale</td>
                    <td>@product.TotalSales</td>
        </tr>
    }
        </tbody>
</table>
    </div>
    <div class="add-row-product-view ">
    <div>@Html.ActionLink("Retour à l'accueil", "Index", "Home", null, new { @class = "return-catalog" })</div>
    <div>@Html.ActionLink("Retour à mon compte", "Index", "Account", null, new { @class = "return-catalog" })</div>
    </div>
</div>

AMAPG4/Views/Producer/ProducerView.cshtml
@using AMAPG4.Models.User
@using AMAPG4.Models.Catalog
@model AMAPG4.ViewModels.ProducerViewModel

@{
	ViewBag.Title = "Détails des producteurs";
	Layout = "_Layout";
}
<link rel="stylesheet" href="~/css/laFerme.css" />
<link rel="stylesheet" href="~/css/styles.css" />
<div class="product-detail-body">
	<div class="product-container">
		<img class="product-photo" src="@Model.Producers.ImagePath" />
		<div class="product-details">
			<h2>@Model.Account.Name</h2>

			<p class="product-view-description">@Model.Producers.Description</p>
			
			@foreach (Product product in Model.Products)
			{
				<div class="link-products-producer-view">
								@Html.ActionLink(product.ProductName, "ProductView", "Catalog", new { id = product.Id })
                </div>
			}
		
		</div>

	</div>
	<div class="return-producers">@Html.ActionLink("Retour à la Liste des Producteurs", "Index", "Producer", null, new { @class = "return-catalog" })</div>
</div>

AMAPG4/Views/Producer/Read.cshtml
@model AMAPG4.Models.User.Producer

@{
    ViewBag.Title = "Détails du Producteur";
    Layout = "_BackOfficeLayout";
}
<div class="user-profile-form-container">
    <div class="user-profile">
        <div class="form-header">
            <h1 class="bo-entity">Détails du Producteur n° @Model.Id</h1>
            <a href="@Url.Action("Producers", "Dashboard")" class="btn-action">Retour aux CE</a>
        </div>


    <div class="user-info">
        <label>Nom :</label>
        <span>@Model.Account.Name</span>
    </div>
    <div class="user-info">
        <label>Type de production :</label>
        <span>@Model.ProductionType</span>
    </div>

    <div class="user-info">
        <label>Nom du contact :</label>
        <span>@Model.ContactName</span>
    </div>
    <div class="user-info">
        <label>Description :</label>
        <span>@Model.Description</span>
    </div>

    <div class="user-info">
        <label>Email :</label>
        <span>@Model.Account.Email</span>
    </div>

    <div class="user-info">
        <label>Téléphone :</label>
        <span>@Model.Account.Phone</span>
    </div>

    <div class="user-info">
        <label>Adresse :</label>
        <span>@Model.Account.Address</span>
    </div>

    <div class="user-info">
        <label>SIRET :</label>
        <span>@Model.Siret</span>
    </div>

    <div class="user-info">
        <label>RIB :</label>
        <span>@Model.RIB</span>
    </div>

    <div class="user-actions">              
                <a href="@Url.Action("Update", "Producer", new { id = Model.Id })" class="btn-action btn-update">Modifier</a>
            <form method="post" action="@Url.Action("Delete", "Producer", new { id = Model.Id })" style="display:inline;">
                <button type="submit" class="btn-action btn-delete">Supprimer</button>
        </form>
    </div>

</div>
</div>
<

AMAPG4/Views/Producer/Update.cshtml
@model AMAPG4.Models.User.Producer

@{
    ViewBag.Title = "Modifier le Producteur n° " + Model.Id;
    Layout = "_BackOfficeLayout";
}

<div class="user-profile-form-container">
    <div class="user-profile">
        <div class="form-header">
            <h1 class="bo-entity">Modifier le Producteur n° @Model.Id</h1>
            <a href="@Url.Action("Read", "Producer", new { id = Model.Id })" class="btn-action">Retour</a>
        </div>

        @using (Html.BeginForm("Update", "Producer", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Id)

            <div class="user-info">
                <label>Nom :</label>
                @Html.TextBoxFor(model => model.Account.Name, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>Type de production :</label>
                @Html.TextBoxFor(model => model.ProductionType, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>Nom du contact :</label>
                @Html.TextBoxFor(model => model.ContactName, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>Description :</label>
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>Email :</label>
                @Html.TextBoxFor(model => model.Account.Email, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>Téléphone :</label>
                @Html.TextBoxFor(model => model.Account.Phone, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>Adresse :</label>
                @Html.TextBoxFor(model => model.Account.Address, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>SIRET :</label>
                @Html.TextBoxFor(model => model.Siret, new { @class = "form-control" })
            </div>

            <div class="user-info">
                <label>RIB :</label>
                @Html.TextBoxFor(model => model.RIB, new { @class = "form-control" })
            </div>

            <div class="user-actions">
                <button type="submit" class="btn-validate">Valider</button>
            </div>
        }
    </div>
</div>