AMAPG4/Models/Command/CommandLine.cs
using Microsoft.VisualBasic;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace AMAPG4.Models.Command
{
    public class CommandLine
    {

        public int Id { get; set; }
        public int CommandId { get; set; }
        [Column(TypeName = "decimal(10,2)")]
        public decimal Total { get; set; }
        public int UserId { get; set; }
        public CommandLineType CommandType { get; set; }
        public DateTime DateTimeOrdered { get; set; }
        public DateTime DateTimeDelivered { get; set; }


    }
}

AMAPG4/Models/Command/CommandLineType.cs
namespace AMAPG4.Models.Command
{
    public enum CommandLineType
    {
        In_Progress,
        Paid,
        Delivered,
        Contribution

    }
}

AMAPG4/Models/Command/ICommandLineService.cs
using System;
using System.Collections.Generic;

namespace AMAPG4.Models.Command
{
    public interface ICommandLineService : IDisposable
    {
        public List<CommandLine> GetAllCommandLines();
    }
}

AMAPG4/Models/Command/IOrderLineDal.cs
using System;
using System.Collections.Generic;

namespace AMAPG4.Models.Command
{
    public interface IOrderLineDal : IDisposable
    {
        public List<OrderLine> GetAllOrderLines();
        public int CreateOrderLine(int useraccountId, int quantity, int productid);
        public List<OrderLine> GetCurrentOrderLines(int IdUtilisateur, OrderLineType Reserved);
        public List<OrderLine> GetPastOrderLines(int IdUtilisateur, OrderLineType Paid);
    }
}

AMAPG4/Controllers/CommandController.cs
using AMAPG4.Models.Command;
using AMAPG4.Models.User;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using AMAPG4.ViewModels;
using System.Xml.Schema;
using System;
using System.Linq;
using AMAPG4.Models;
using Microsoft.AspNetCore.Authorization;

namespace AMAPG4.Controllers
{

    public class CommandController : Controller
        
    {
        MyDBContext _bddContext;
        public IActionResult Index()
        {
            OrderLineDal orderLineDal = new OrderLineDal();
            CommandViewModel CommandViewModel = new CommandViewModel();

            using (UserAccountDal userAccountDal = new UserAccountDal())
            {
                CommandViewModel.UserId = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name).Id;

            }
            CommandViewModel.ListOrderline = orderLineDal.GetCurrentOrderLines(CommandViewModel.UserId, OrderLineType.Reserved);
            int CommandId=CommandViewModel.ListOrderline[0].CommandId;
          CommandViewModel.CommandId = CommandId;
        using (CommandLineService commandLine = new CommandLineService())
            {

                commandLine.UpdateTotal(CommandId);
                CommandLine command = commandLine.GetCommandFromId(CommandId);
                CommandViewModel.Total = command.Total;

            }

          
            CommandViewModel.CommandToLookAt = 0;

            return View(CommandViewModel);
        }



        public IActionResult PastOrder()
        {
            CommandViewModel CommandViewModel = new CommandViewModel();
            OrderLineDal orderLineDal = new OrderLineDal();
            using (UserAccountDal userAccountDal = new UserAccountDal())
            {
                CommandViewModel.UserId = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name).Id;

            }
            using (CommandLineService commandLineService = new CommandLineService())
            {
                CommandViewModel.AllFromUser = commandLineService.GetAllCommandFromUser(CommandViewModel.UserId);
                foreach (CommandLine command in CommandViewModel.AllFromUser)
                {
                    commandLineService.UpdateTotal(command.CommandId);
                }

            }
    
         

            return View(CommandViewModel);
        }
        [HttpPost]
        public IActionResult PastOrder(CommandViewModel CommandViewModel)
        {

            OrderLineDal orderLineDal = new OrderLineDal();
            Console.Write(CommandViewModel.CommandToLookAt);
            using (UserAccountDal userAccountDal = new UserAccountDal())
            {
                CommandViewModel.UserId = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name).Id;

            }
            using (CommandLineService commandLineService = new CommandLineService())
            {
                CommandViewModel.AllFromUser = commandLineService.GetAllCommandFromUser(CommandViewModel.UserId);
                CommandViewModel.ListOrderline = commandLineService.GetAllOrderLineFromCommand(CommandViewModel.CommandToLookAt);
                
            }
            

      
            return View(CommandViewModel);
        }
        public IActionResult Payment(CommandViewModel commandViewModel)
        {
            // INTEGRER UNE API ICI
            
        Console.Write(commandViewModel.CommandId);
            Console.Write(commandViewModel.CommandType);
            OrderLineDal orderLineDal = new OrderLineDal();
			using (UserAccountDal userAccountDal = new UserAccountDal())
			{
				if (userAccountDal.GetUserAccount(HttpContext.User.Identity.Name) != null)
                 {
			
					commandViewModel.UserId = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name).Id;

				}
			}
   
            commandViewModel.ListOrderline = orderLineDal.GetCurrentOrderLines(commandViewModel.UserId, OrderLineType.Reserved);
            if (commandViewModel.ListOrderline == null)
            {
                commandViewModel.ListOrderline = orderLineDal.GetCurrentOrderLines(commandViewModel.UserId, OrderLineType.Contribution);
                if (commandViewModel.ListOrderline == null)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            foreach (OrderLine orderline in commandViewModel.ListOrderline)
            {
                commandViewModel.CommandId = orderline.CommandId;
            }
            PaymentViewModel paymentViewModel = new PaymentViewModel();
            using (CommandLineService commandLineService = new CommandLineService())
            {
                paymentViewModel.CommandLine = commandLineService.GetAllCommandLines().FirstOrDefault(c => c.CommandId == commandViewModel.CommandId);
                Console.WriteLine(paymentViewModel.CommandLine.CommandId);
                Console.WriteLine(paymentViewModel.CommandLine.CommandType);
            }
            paymentViewModel.IsConfirmed = false;
            paymentViewModel.status = StatusType.Waiting;

            return View(paymentViewModel);
        }
        [HttpPost]
        public IActionResult Payment(PaymentViewModel paymentViewModel)
        {
            // INTEGRER UNE API ICI

            if (paymentViewModel.CardNum == "1111111111111111") // Numero de carte pour EXPEMPLE SEULEMENT
            {
                
                using (CommandLineService commandLineService = new CommandLineService())
                {
                    paymentViewModel.CommandLine = commandLineService.GetAllCommandLines().FirstOrDefault(c => c.CommandId == paymentViewModel.CommandId);
                    Console.WriteLine(paymentViewModel.CommandLine.CommandId);
                    Console.WriteLine(paymentViewModel.CommandLine.CommandType);
                    if (paymentViewModel.CommandLine.CommandType == CommandLineType.Contribution)
                    {
                        int id = paymentViewModel.CommandLine.UserId;
                        using (IndividualDal userAccountDal = new IndividualDal())
                        {
                           userAccountDal.UpdateContribition(id);
           
                        }

                    }
                    else
                    {
                        commandLineService.UpdateCommandLine(paymentViewModel.CommandId, CommandLineType.Paid);
                    }
                    
                    paymentViewModel.CommandLine = commandLineService.GetAllCommandLines().FirstOrDefault(c => c.CommandId == paymentViewModel.CommandId);
                    paymentViewModel.status = StatusType.Success;
                    
                  
                }
            }
            else
            {
                using (CommandLineService commandLineService = new CommandLineService())
                {
                    paymentViewModel.CommandLine = commandLineService.GetAllCommandLines().FirstOrDefault(c => c.CommandId == paymentViewModel.CommandId);
                }
                paymentViewModel.status = StatusType.Failed;
           
            }

          

            return View(paymentViewModel);
        }
    }
}

AMAPG4/Controllers/LoginController.cs
using AMAPG4.Models.Command;
using AMAPG4.Models.User;
using AMAPG4.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace AMAPG4.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            UserAccountViewModel UserAccountViewModel =
                new UserAccountViewModel() { Authentication = HttpContext.User.Identity.IsAuthenticated };
            if (UserAccountViewModel.Authentication)
            {
                using (UserAccountDal userAccountDal = new UserAccountDal())
                {
                    UserAccountViewModel.UserAccount = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name);
                }
                return View(UserAccountViewModel);
            }
            return View(UserAccountViewModel);
        }
        [HttpPost]
        public IActionResult Index(UserAccountViewModel viewModel, string returnUrl)
        {
            // Liste des champs qu'on veut garder dans le ModelState
            string[] fieldsToKeep = { "UserAccount.Email", "UserAccount.Password" };

            // On supprime tous les autres champs du ModelState
            foreach (string key in ModelState.Keys.ToList())
            {
                if (!fieldsToKeep.Contains(key))
                {
                    ModelState.Remove(key);
                }
            }

            //On ne vérifie que les champs Email et Password
            if (ModelState.IsValid)
            {
    
                using (UserAccountDal userAccountDal = new UserAccountDal())
                {   //On vérifie qu'un utilisateur avec ce Nom + MDP existe en allant le chercher dans la BDD
                    UserAccount userAccount =
                        userAccountDal.Authentication(viewModel.UserAccount.Email, viewModel.UserAccount.Password);

                    if (userAccount != null)
                    {
                        List<Claim> userClaims = new List<Claim>()
                        {
                            new Claim(ClaimTypes.Name, userAccount.Id.ToString()),
                            new Claim(ClaimTypes.Role, userAccount.Role.ToString())

                        };

                        ClaimsIdentity claimsIdentity = new ClaimsIdentity(userClaims, "User Identity");
                        ClaimsPrincipal userPrincipal = new ClaimsPrincipal(new[] { claimsIdentity });

                        HttpContext.SignInAsync(userPrincipal);
                    }
                    else
                    {
                        ModelState.AddModelError("UserAccount.Email", "Email et/ou mot de passe incorrect(s)");
                    }
                }
                if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                {

                    return Redirect(returnUrl);
                }

                return Redirect("/");
            }

            return View(viewModel);
        }

        public IActionResult CreateIndividualAccount()
        {
            ModelState.Clear();

			return View();
        }

        [HttpPost]
        public IActionResult CreateIndividualAccount(CreateUserAccountViewModel createUserAccountViewModel)
        {

                                                              
                if (ModelState.IsValid)
            {
 
                using (IndividualDal individualDal = new IndividualDal())
                {
                  

                    // Validation  
                    if (createUserAccountViewModel.UserAccount.Password != createUserAccountViewModel.ConfirmPassword)
                    {
                        ModelState.AddModelError("ConfirmPassword", "Les mots de passe ne correspondent pas.");
                    }

                   
                    // Vérifier si l'email existe déjà  
                    //if (_bddContext.UserAccounts.Any(u => u.Email == email))  
                    //{  
                    //throw new ArgumentException("Un utilisateur avec cet email existe déjà.");  
                    //}  
          
                    int id = individualDal.CreateIndividual(

                        createUserAccountViewModel.Individual.FirstName,
                        DateTime.Now,
                        false,
                        createUserAccountViewModel.Individual.IsVolunteer,
                        createUserAccountViewModel.UserAccount.Email,
                        createUserAccountViewModel.UserAccount.Password,
                        createUserAccountViewModel.UserAccount.Name,
                        createUserAccountViewModel.UserAccount.Address,
                        createUserAccountViewModel.UserAccount.Phone);
					CommandViewModel commandViewModel = new CommandViewModel();
                    OrderLineDal orderLineDal = new OrderLineDal();
                    
                        Individual Indie =individualDal.GetIndividualById(id);
                        Console.WriteLine(Indie.Account.Id);
						OrderLine orderline= orderLineDal.CreateContribution(Indie.Account.Id);
                        commandViewModel.CommandId = orderline.CommandId;
                        commandViewModel.CommandType = CommandLineType.Contribution;
                        commandViewModel.UserId = Indie.Account.Id;
                    
                   
                  

           
                    return RedirectToAction("Payment", "Command", commandViewModel);
				}
            }
     

            return View();
        }

        public IActionResult Deconnexion()
        {
            HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }
}

AMAPG4/Controllers/OrderController.cs
using AMAPG4.Models.User;
using Microsoft.AspNetCore.Mvc;
using AMAPG4.ViewModels;
using AMAPG4.Models.Command;
using System.Security.Cryptography.X509Certificates;
using System.Collections.Generic;
using AMAPG4.Models.Catalog;
using System;

namespace AMAPG4.Controllers
{
    public class OrderController : Microsoft.AspNetCore.Mvc.Controller
    {
        public IActionResult Index()
        {
            UserAccountViewModel UserAccountViewModel =
                new UserAccountViewModel();
            OrderLineViewModel OrderLineViewModel =
                new OrderLineViewModel();
            using (UserAccountDal userAccountDal = new UserAccountDal())
            {
                UserAccountViewModel.UserAccount = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name);

            }

            OrderLineDal orderLineDal = new OrderLineDal();

            OrderLineViewModel.UserActualId = UserAccountViewModel.UserAccount.Id;
            OrderLineViewModel.OrderLinesTotal = orderLineDal.GetPastOrderLines(UserAccountViewModel.UserAccount.Id, OrderLineType.Paid);
            OrderLineViewModel.OrderLinesCurrent = orderLineDal.GetCurrentOrderLines(UserAccountViewModel.UserAccount.Id, OrderLineType.Reserved);
            foreach (OrderLine orderLine in OrderLineViewModel.OrderLinesCurrent)
            {
                OrderLineViewModel.Total = orderLine.Total + OrderLineViewModel.Total;
            }


            return View(OrderLineViewModel); // mettre vue du panier et afficher l'id utilisateur ;
        }
        [HttpPost]
        public IActionResult Index(OrderLineViewModel orderLineViewModel)
        {

            OrderLineDal orderLineDal = new OrderLineDal();
            OrderLine orderLine = orderLineDal.GetOrderLineById(orderLineViewModel.OrderLineId);
            orderLineDal.UpdateQuantityFromCart(orderLine, orderLineViewModel.NewQuantity);

            UserAccountViewModel UserAccountViewModel =
                                           new UserAccountViewModel();
            using (UserAccountDal userAccountDal = new UserAccountDal())
            {
                UserAccountViewModel.UserAccount = userAccountDal.GetUserAccount(HttpContext.User.Identity.Name);

            }



            orderLineViewModel.UserActualId = UserAccountViewModel.UserAccount.Id;
            orderLineViewModel.OrderLinesTotal = orderLineDal.GetPastOrderLines(UserAccountViewModel.UserAccount.Id, OrderLineType.Paid);
            orderLineViewModel.OrderLinesCurrent = orderLineDal.GetCurrentOrderLines(UserAccountViewModel.UserAccount.Id, OrderLineType.Reserved);
            //orderLineViewModel1.OrderLine = null;


            // Calcul du total
            foreach (OrderLine orderline in orderLineViewModel.OrderLinesCurrent)
            {
                orderLineViewModel.Total = orderline.Total + orderLineViewModel.Total;
            }




            return View(orderLineViewModel);
        }


    }
}

AMAPG4/Views/Command/Index.cshtml
@using AMAPG4.Models.Catalog
@using AMAPG4.Models.Command


@model AMAPG4.ViewModels.CommandViewModel
@{

    Layout = "_layout";
}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/global.css">
<link rel="stylesheet" href="/css/styles.css">
<link rel="stylesheet" href="~/css/laFerme.css" />
    <title>Résumé de la commande</title>
<div class=" activity-body">
<h3>
<h2 class="welcome-text">
            Résumé de la commande N° : @Model.CommandId
        </h2>

    <table class=" table-product">
        <thead>
            <tr>
                <th>Nom du produit</th>
            <th>Quantité</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
    @foreach (OrderLine orderLine in Model.ListOrderline)
    {<tr>
                <td>@orderLine.Product.ProductName</td>
                <td>@orderLine.Quantity</td>
                <td>@orderLine.Total</td>
       
            </tr>
    }
    </tbody>
    <tfoot>
        <tr>
        <th></th>
    <th>Total :  </th>
    <th>@Model.Total</th>
        </tr>
    </tfoot>

</table>
        <div class="add-row-product-view ">
            <a href="@Url.Action("Payment", "Command")" class="btn-save">Passer au paiement</a>

        </div>
<div class="add-row-product-view ">
    <div>@Html.ActionLink("Retour au panier", "Index", "Order", null, new { @class = "return-catalog" })</div>
</div>



</h3>
</div>

AMAPG4/Views/Command/PastOrder.cshtml
@using AMAPG4.Models.Catalog
@using AMAPG4.Models.Command


@model AMAPG4.ViewModels.CommandViewModel

@{

    Layout = "_layout";
}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="stylesheet" href="/css/global.css">
<link rel="stylesheet" href="~/css/laFerme.css" />
    <title>Panier</title>


    <h2 class="welcome-text">Votre historique de commande :</h2>
    <table class="table-product">
        <thead>
        <tr>
           <th>Numéro de commande</th>
            <th>Date de commande</th>
            <th>Date de Livraison</th>
            
            <th>Status de la Commande</th>
            <th>Total</th>
            <th></th>
        </tr>
        </thead>
    @foreach (CommandLine commandLine in Model.AllFromUser )
    {
       if(commandLine.CommandType != CommandLineType.Contribution)
        {
        <tbody>
            <tr>
                <td>@commandLine.CommandId </td>
                <td>@commandLine.DateTimeOrdered.ToShortDateString()</td>
              

                @if (@commandLine.CommandType == CommandLineType.In_Progress)
                {
                    <td>A déterminer</td>
                    <td>Commande dans le panier</td>
                }
                else if (@commandLine.CommandType == CommandLineType.Paid)
                {
                    <td>@commandLine.DateTimeDelivered.ToShortDateString()</td>
                    <td>Commande en attente</td>
                }
                else
                {
                    <td>@commandLine.DateTimeDelivered.ToShortDateString()</td>
                    <td>Commande terminée</td>
                }
                <td>@commandLine.Total</td>
  
        @using (Html.BeginForm("PastOrder", "Command")){

            <input type="hidden" name="CommandToLookAt" value="@commandLine.CommandId" />


                    <td>
                        <input type="submit" value="Détail" />
                    </td>
        }
                
            </tr>
            </tbody>
        if (Model.CommandToLookAt == @commandLine.CommandId)
   
        {
            <thead>
                <tr>
                    <th>Nom du Produit</th>

                    <th>Prix</th>
                    <th>Quantité </th>
                    <th> Total </th>
                   
                </tr>
                </thead>
            foreach (OrderLine orderLine in Model.ListOrderline)
            {
                <tbody>
                 <tr>
                <td>@orderLine.Product.ProductName</td>
                        
                    <td>@orderLine.Product.Price €</td>
                        <td>@orderLine.Quantity </td>
                        <td> @orderLine.Total </td>
                       
                        </tr>
                    </tbody>
                }
            }
        }
 
    }
    </table>
<div class="add-row-product-view ">
    <a href="@Url.Action("Index", "Account")" class="btn-save">Retour à mon compte</a>
    <div>@Html.ActionLink("Retour à l'accueil", "Index", "Home", null, new { @class = "return-catalog" })</div>
</div>

AMAPG4/Views/Command/Payment.cshtml
@model AMAPG4.ViewModels.PaymentViewModel

@{

	Layout = "_layout";
}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/css/styles.css">
<link rel="stylesheet" href="/css/global.css">
<link rel="stylesheet" href="/css/forms.css">
<link rel="stylesheet" href="/css/laFerme.css">
<title>Paiement</title>

@if (Model.status == AMAPG4.Models.StatusType.Failed || Model.status == AMAPG4.Models.StatusType.Waiting)
{

	<div class="container">
		<div class="form-container">

			@using (Html.BeginForm())
			{
				<fieldset class="fieldset-style">
					<legend>Paiement</legend>
					@if (Model.status == AMAPG4.Models.StatusType.Failed)
					{
						<div></div>
						<div class="RejectedMessage">Le paiement a été refusé</div>
					}
					<p class="welcome-text"> Vous serez facturé pour un total de @Model.CommandLine.Total €</p>
					<input type="hidden" name="CommandId" value="@Model.CommandLine.CommandId" />
					<p> @Html.TextBoxFor(m => m.FirstName, new { @placeholder = "Prénom" })  @Html.TextBoxFor(m => m.LastName, new { @placeholder = "Nom" })</p>
					<p>@Html.TextBoxFor(m => m.CardNum, new { @placeholder = "Numéro de Carte" })</p>
					<p>@Html.TextBoxFor(m => m.SecretCode, new { @placeholder = "CVV" })</p>
							 <img class="payment-img" src="~/images/visa-mc-paypal.png" />

					<input type="submit" value="Payer" />
				</fieldset>
			}

		</div>
	</div>
}
else if (Model.status == AMAPG4.Models.StatusType.Success && Model.CommandLine.CommandType == AMAPG4.Models.Command.CommandLineType.Contribution)
{
	<h2 class="welcome-text">Votre contribution a bien été enregistrée ! </h2>
	<div class="add-row-product-view ">
		<div>@Html.ActionLink("Retourner à la connexion", "Index", "Login", null, new { @class = "return-catalog" })</div>
	</div>
}
else if (Model.status == AMAPG4.Models.StatusType.Success)
{
	<div class="checkout">
	<h2 class="welcome-text">Merci pour votre commande ! Vous pourrez venir la chercher aux locaux de l'AMAP le Vendredi @Model.CommandLine.DateTimeDelivered.Day @Model.CommandLine.DateTimeDelivered.ToString("MMMM") !</h2>
	<img src="~/images/icons/checkout.png" />
	
	<div class="add-row-product-view ">
		<div>@Html.ActionLink("Retourner à l'accueil", "Index", "Home", null, new { @class = "return-catalog" })</div>
	</div>
	</div>
}